function [x_opt, fval, history] = pso_for_step1(swarm_size, max_stalls, Initial_position, Lower_bound, Upper_bound,data)

    history = [];    
    options = optimoptions('particleswarm',...
                       'SwarmSize',swarm_size,...
                       'MaxStallIterations',max_stalls,...
                       'PlotFcn','pswplotbestf',...
                       'FunctionTolerance',0.5e-9,...
                       'ObjectiveLimit',10,...
                       'InitialSwarmMatrix',Initial_position,...
                       'Display','iter',...
                       'SocialAdjustmentWeight',2,...
                       'SelfAdjustmentWeight',1, ...
                       'UseParallel',true, ...
                       'OutputFcn', @myoutput);

    [x_opt,fval,exitflag,output] = particleswarm(@(x) Half_Cell_main(x,data),...
        length(Initial_position), ...
    Lower_bound, Upper_bound, options);
        
    function stop = myoutput(optimValues,state)
        stop = false;

    end
     
end